_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 1
                - 5
                - 12
                - 45
                - 53
                - 55
            "2":
                - 1
                - 5
                - 12
                - 45
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.13.1
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
